### PR TITLE
Misc. bag of contributions

### PR DESCRIPTION
**Pull request by pmonks**
A small series of contributions comprising:
- Upgraded dependencies
- Eliminated reflection warnings
- Added notes regarding `save-cursor` and `restore-cursor` not functioning on most terminals

### CODE REVIEW

**Comment by xsc** [comment]
I cannot recall ever seeing this PR. Sorry for never responding and thank you, @pmonks!

**Comment by pmonks** [comment]
No worries, and thank you for putting such a handy library out there as open source!

**Comment by pmonks** [comment]
In terms of getting a build out with this updated code in it, would you be interested in automatic deployment for jansi-clj?

I have it setup on a few of my projects, for both the JARs and the docs, and it's extremely handy.  In fact [my project that's using jansi-clj](https://github.com/pmonks/spinner) has this configured, and it's pretty straight forward using TravisCI.  Most of the magic is in the [.travis.yml](https://github.com/pmonks/spinner/blob/master/.travis.yml), with a little bit of deploy plugin config in [project.clj](https://github.com/pmonks/spinner/blob/master/project.clj#L34-L41).  This setup deploys snapshots to clojars and codox docs to GitHub Pages on every commit to the master branch - the only thing it can't do is deploy non-snapshot releases (since clojars requires those to be signed, and I haven't yet taken the time to figure out if it's possible / safe to share my private key with TravisCI).

**Comment by xsc** [comment]
@pmonks I'll have a look, thanks! In the meantime, I released `0.1.1` with your changes. :)

**Pull request merged**
