### PR TITLE
Fix for issue 4

### PR DESCRIPTION
**Pull request by pmonks**
This PR fixes issue #4 ("x and y args to cursor! are reversed").

### CODE REVIEW

**Comment by xsc** [comment]
Thanks! I know it seems slightly weird, but I wouldn't change the function signature (for backwards compatibility plus, traditionally, having x as the first parameter seems right).

Could you make that adjustment (i.e. revert the change to the function signature)?

**Comment by pmonks** [comment]
Sure. Just to clarify, you want me to reverse the args inside the `cursor!` fn, when the underlying jansi API is called?

**Comment by pmonks** [comment]
Not weird at all - what's weird is the order of those args in jansi itself.  😉

**Review by xsc — APPROVED** [review]

**Comment by xsc** [comment]
Merged. Thanks! I can't release right now but I'll do it asap!

**Pull request merged**
